apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: names
  labels:
    strimzi.io/cluster: my-cluster
  namespace: quarkus-workshop
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
